from dspy import Example

train_set = [
    Example(
        text="Plan 3 healthy dinners for a family of 4. We prefer Asian or Mediterranean food, avoid gluten and dairy, and want high protein meals under 600 calories.",
        output={
            "query": None,
            "cuisine": ["ASIAN", "MEDITERRANEAN"],
            "excludeCuisine": None,
            "diet": ["GLUTEN_FREE"],
            "intolerances": ["DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 4,
            "minFiber": None,
            "minProtein": 25,
            "maxCalories": 600,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Give me 2 vegan lunch ideas with no soy or peanuts, good fiber content, and under 30g of carbs.",
        output={
            "query": None,
            "cuisine": None,
            "excludeCuisine": None,
            "diet": ["VEGAN"],
            "intolerances": ["SOY", "PEANUT"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 1,
            "minFiber": 5,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": 30,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 2
        }
    ),
    Example(
        text="I need 5 quick breakfast recipes for 2 people. Avoid seafood and shellfish. Keep fat under 15g and sodium low.",
        output={
            "query": "quick",
            "cuisine": None,
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["SEAFOOD", "SHELLFISH"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "BREAKFAST",
            "minServings": 2,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": 15,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": 500,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    ),
    Example(
        text="Suggest 4 Italian meals for 3 people that are vegetarian, low in saturated fat and cholesterol, and include tomatoes.",
        output={
            "query": None,
            "cuisine": ["ITALIAN"],
            "excludeCuisine": None,
            "diet": ["VEGETARIAN"],
            "intolerances": None,
            "includeIngredients": ["tomatoes"],
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 3,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": 100,
            "maxSaturatedFat": 3,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 4
        }
    ),
    Example(
        text="Make a single Mediterranean appetizer for 2 people without grains or tree nuts, and under 100mg cholesterol.",
        output={
            "query": None,
            "cuisine": ["MEDITERRANEAN"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["GRAIN", "TREE_NUT"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "APPETIZER",
            "minServings": 2,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": 100,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 1
        }
    ),
    Example(
        text="Plan 7 dinners for 2 people that are pescatarian and include Mediterranean or Japanese cuisine. Keep each meal under 500 calories and low sodium.",
        output={
            "query": None,
            "cuisine": ["MEDITERRANEAN", "JAPANESE"],
            "excludeCuisine": None,
            "diet": ["PESCATARIAN"],
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 2,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": 500,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": 500,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 7
        }
    ),
    Example(
        text="Give me 3 side dishes with Indian flavors, no eggs or dairy, suitable for a paleo diet.",
        output={
            "query": None,
            "cuisine": ["INDIAN"],
            "excludeCuisine": None,
            "diet": ["PALEO"],
            "intolerances": ["EGG", "DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SIDE",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Suggest 2 keto-friendly snacks under 200 calories each with no gluten, sesame, or wheat.",
        output={
            "query": None,
            "cuisine": None,
            "excludeCuisine": None,
            "diet": ["KETOGENIC"],
            "intolerances": ["GLUTEN", "SESAME", "WHEAT"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SNACK",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": 200,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 2
        }
    ),
    Example(
        text="I need 6 American-style main courses for 5 people that are Whole30 compliant and avoid tree nuts and shellfish.",
        output={
            "query": None,
            "cuisine": ["AMERICAN"],
            "excludeCuisine": None,
            "diet": ["WHOLE30"],
            "intolerances": ["TREE_NUT", "SHELLFISH"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 5,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 6
        }
    ),
    Example(
        text="Give me one French dessert under 300 calories for a gluten-free, lactose-intolerant friend.",
        output={
            "query": None,
            "cuisine": ["FRENCH"],
            "excludeCuisine": None,
            "diet": ["GLUTEN_FREE"],
            "intolerances": ["DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "DESSERT",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": 300,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 1
        }
    ),
    Example(
        text="Provide 4 quick Italian lunches for 2 that are low in carbs and fat.",
        output={
            "query": "quick",
            "cuisine": ["ITALIAN"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 2,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": 30,
            "maxFat": 15,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 4
        }
    ),
    Example(
        text="List 5 Mexican meals for 4 people that are high in fiber and protein, avoid soy and seafood.",
        output={
            "query": None,
            "cuisine": ["MEXICAN"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["SOY", "SEAFOOD"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 4,
            "minFiber": 5,
            "minProtein": 25,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    ),
    Example(
        text="Make a single Korean fingerfood recipe with less than 10g fat and no peanuts.",
        output={
            "query": None,
            "cuisine": ["KOREAN"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["PEANUT"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "FINGERFOOD",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": 10,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 1
        }
    ),
    Example(
        text="Suggest 3 Nordic breakfast recipes for 2 people that are low in cholesterol and saturated fat.",
        output={
            "query": None,
            "cuisine": ["NORDIC"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "BREAKFAST",
            "minServings": 2,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": 100,
            "maxSaturatedFat": 3,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Give me 2 soups that are vegan and low sodium, avoid shellfish and sesame.",
        output={
            "query": None,
            "cuisine": None,
            "excludeCuisine": None,
            "diet": ["VEGAN"],
            "intolerances": ["SHELLFISH", "SESAME"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SOUP",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": 500,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 2
        }
    ),
    Example(
        text="Find 3 Latin American snacks for a low-FODMAP diet with fewer than 400 calories.",
        output={
            "query": None,
            "cuisine": ["LATIN_AMERICAN"],
            "excludeCuisine": None,
            "diet": ["LOW_FODMAP"],
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SNACK",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": 400,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Provide 5 Chinese dinners for 3 people that are low fat, avoid sulfites and soy, and include mushrooms.",
        output={
            "query": None,
            "cuisine": ["CHINESE"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["SULFITE", "SOY"],
            "includeIngredients": ["mushrooms"],
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 3,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": 15,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    ),
    Example(
        text="One Mediterranean bread recipe without dairy or wheat for a vegan diet.",
        output={
            "query": None,
            "cuisine": ["MEDITERRANEAN"],
            "excludeCuisine": None,
            "diet": ["VEGAN"],
            "intolerances": ["DAIRY", "WHEAT"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "BREAD",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 1
        }
    ),
    Example(
        text="Show 4 Caribbean dishes with high fiber and under 30g of carbs, no grain or dairy.",
        output={
            "query": None,
            "cuisine": ["CARIBBEAN"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["GRAIN", "DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 1,
            "minFiber": 5,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": 30,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 4
        }
    ),
    Example(
        text="Give me 5 quick Mediterranean lunches for 2 people that are high in protein and dairy-free.",
        output={
            "query": "quick",
            "cuisine": ["MEDITERRANEAN"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 2,
            "minFiber": None,
            "minProtein": 25,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    ),
    Example(
        text="Suggest 3 Vietnamese soups for dinner that are Whole30 compliant and low sodium.",
        output={
            "query": None,
            "cuisine": ["VIETNAMESE"],
            "excludeCuisine": None,
            "diet": ["WHOLE30"],
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SOUP",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": 500,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="I want 4 Italian snacks that are vegetarian, gluten-free, and contain olives.",
        output={
            "query": None,
            "cuisine": ["ITALIAN"],
            "excludeCuisine": None,
            "diet": ["VEGETARIAN", "GLUTEN_FREE"],
            "intolerances": None,
            "includeIngredients": ["olives"],
            "excludeIngredients": None,
            "type": "SNACK",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 4
        }
    ),
    Example(
        text="Find 2 Spanish desserts for 3 people that are under 400 calories and nut-free.",
        output={
            "query": None,
            "cuisine": ["SPANISH"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["TREE_NUT", "PEANUT"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "DESSERT",
            "minServings": 3,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": 400,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 2
        }
    ),
    Example(
        text="I need 3 paleo-friendly Caribbean dinners without soy or sesame, each serving 4.",
        output={
            "query": None,
            "cuisine": ["CARIBBEAN"],
            "excludeCuisine": None,
            "diet": ["PALEO"],
            "intolerances": ["SOY", "SESAME"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 4,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="List 5 gluten-free Asian breakfasts with at least 6g of fiber and no dairy.",
        output={
            "query": None,
            "cuisine": ["ASIAN"],
            "excludeCuisine": None,
            "diet": ["GLUTEN_FREE"],
            "intolerances": ["DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "BREAKFAST",
            "minServings": 1,
            "minFiber": 6,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    ),
    Example(
        text="I want a single Japanese lunch with less than 300 calories, no eggs, and rich in fiber.",
        output={
            "query": None,
            "cuisine": ["JAPANESE"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["EGG"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 1,
            "minFiber": 5,
            "minProtein": None,
            "maxCalories": 300,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 1
        }
    ),
    Example(
        text="Find 4 vegan main courses for 2 people using lentils and tomatoes.",
        output={
            "query": None,
            "cuisine": None,
            "excludeCuisine": None,
            "diet": ["VEGAN"],
            "intolerances": None,
            "includeIngredients": ["lentils", "tomatoes"],
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 2,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 4
        }
    ),
    Example(
        text="Show me 3 low-fat Greek dishes with chickpeas, no gluten or soy.",
        output={
            "query": None,
            "cuisine": ["GREEK"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["GLUTEN", "SOY"],
            "includeIngredients": ["chickpeas"],
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": 10,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Provide 5 Indian dinners that are high in protein, vegetarian, and under 500 calories.",
        output={
            "query": None,
            "cuisine": ["INDIAN"],
            "excludeCuisine": None,
            "diet": ["VEGETARIAN"],
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 1,
            "minFiber": None,
            "minProtein": 20,
            "maxCalories": 500,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    )
]

dev_set = [
    Example(
        text="Give me 3 gluten-free and vegan Mediterranean lunch ideas for 2 people, with at least 5g of fiber.",
        output={
            "query": None,
            "cuisine": ["MEDITERRANEAN"],
            "excludeCuisine": None,
            "diet": ["VEGAN", "GLUTEN_FREE"],
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 2,
            "minFiber": 5,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Find 2 Japanese dinners for 4 people that are low in sodium, no seafood, and under 300 calories.",
        output={
            "query": None,
            "cuisine": ["JAPANESE"],
            "excludeCuisine": None,
            "diet": None,
            "intolerances": ["SEAFOOD"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "MAIN",
            "minServings": 4,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": 300,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": 500,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 2
        }
    ),
    Example(
        text="Suggest 3 low-carb keto-friendly Italian side dishes that are dairy-free.",
        output={
            "query": None,
            "cuisine": ["ITALIAN"],
            "excludeCuisine": None,
            "diet": ["KETOGENIC"],
            "intolerances": ["DAIRY"],
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SIDE",
            "minServings": 1,
            "minFiber": None,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": 20,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 3
        }
    ),
    Example(
        text="Find 5 Mexican salads for 2 people that are high in fiber, gluten-free, and vegan.",
        output={
            "query": None,
            "cuisine": ["MEXICAN"],
            "excludeCuisine": None,
            "diet": ["VEGAN", "GLUTEN_FREE"],
            "intolerances": None,
            "includeIngredients": None,
            "excludeIngredients": None,
            "type": "SALAD",
            "minServings": 2,
            "minFiber": 5,
            "minProtein": None,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 5
        }
    ),
    Example(
        text="Suggest 2 high-protein pescatarian appetizers with shrimp and no nuts.",
        output={
            "query": None,
            "cuisine": None,
            "excludeCuisine": None,
            "diet": ["PESCATARIAN"],
            "intolerances": ["TREE_NUT", "PEANUT"],
            "includeIngredients": ["shrimp"],
            "excludeIngredients": None,
            "type": "APPETIZER",
            "minServings": 1,
            "minFiber": None,
            "minProtein": 20,
            "maxCalories": None,
            "maxCarbs": None,
            "maxFat": None,
            "maxCholesterol": None,
            "maxSaturatedFat": None,
            "maxSodium": None,
            "instructionsRequired": True,
            "addRecipeInstructions": True,
            "addRecipeNutrition": True,
            "offset": 0,
            "number": 2
        }
    )
]
