import dspy

# This data is used to train and optimize the DSPy information extraction module
# Generated by ChatGPT :)
train_set = [
    dspy.Example(
        text="Plan three meals for two adults and one child. We are pescatarian and prefer Mediterranean food. Avoid peanuts and lamb.",
        meal_count=3,
        people_per_meal=[2, 2, 3],
        diet_restrictions=["pescatarian"],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["peanuts", "lamb"]
    ).with_inputs("text"),

    dspy.Example(
        text="I need six meals for a rotating group of four to six people. Some are vegan, and we aim for high-protein meals. We love Mexican flavors but dislike Indian cuisine.",
        meal_count=6,
        people_per_meal=[4, 5, 6, 4, 5, 6],
        diet_restrictions=["vegan"],
        nutrition_targets=["high-protein"],
        cuisine_likes=["Mexican"],
        cuisine_dislikes=["Indian"],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Design one quick meal for two people. No dietary restrictions, but it must be low-carb and feature Thai flavors. Avoid beef and soy products.",
        meal_count=1,
        people_per_meal=[2],
        diet_restrictions=[],
        nutrition_targets=["low-carb"],
        cuisine_likes=["Thai"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["beef", "soy"]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare five meals for a family of five, including two who are gluten-free. They love Italian and French cuisine but dislike spicy food and cilantro.",
        meal_count=5,
        people_per_meal=[5, 5, 5, 5, 5],
        diet_restrictions=["gluten-free"],
        nutrition_targets=[],
        cuisine_likes=["Italian", "French"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["spicy food", "cilantro"]
    ).with_inputs("text"),

    dspy.Example(
        text="Help me plan two meals for three people. We have one person following keto, and another trying to boost iron intake. We like American food but can't stand Korean dishes.",
        meal_count=2,
        people_per_meal=[3, 3],
        diet_restrictions=["keto"],
        nutrition_targets=["high-iron"],
        cuisine_likes=["American"],
        cuisine_dislikes=["Korean"],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create a brunch and dinner for seven guests. One is vegetarian, another allergic to strawberries. Everyone loves Mediterranean food and dislikes anything too sweet.",
        meal_count=2,
        people_per_meal=[7, 7],
        diet_restrictions=["vegetarian", "strawberry allergy"],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["too sweet foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan one meal for ten people celebrating a birthday. Two guests are lactose intolerant. We want Japanese food and absolutely no pork.",
        meal_count=1,
        people_per_meal=[10],
        diet_restrictions=["lactose intolerant"],
        nutrition_targets=[],
        cuisine_likes=["Japanese"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["pork"]
    ).with_inputs("text"),

    dspy.Example(
        text="Suggest four meals for two adults and two kids. No restrictions, but we prefer heart-healthy options. Favorites are Indian and Thai cuisines.",
        meal_count=4,
        people_per_meal=[4, 4, 4, 4],
        diet_restrictions=[],
        nutrition_targets=["heart-healthy"],
        cuisine_likes=["Indian", "Thai"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="I need three meals for one person with Celiac disease and another who is on a dairy-free diet. We love Moroccan flavors and dislike American fast food.",
        meal_count=3,
        people_per_meal=[2, 2, 2],
        diet_restrictions=["gluten-free", "dairy-free"],
        nutrition_targets=[],
        cuisine_likes=["Moroccan"],
        cuisine_dislikes=["American fast food"],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Organize seven small meals for one adult. I am following paleo, need fiber-rich meals, and I love Mediterranean and hate Mexican food.",
        meal_count=7,
        people_per_meal=[1, 1, 1, 1, 1, 1, 1],
        diet_restrictions=["paleo"],
        nutrition_targets=["high-fiber"],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=["Mexican"],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan two meals for four people with diabetes. We prefer Asian cuisine and dislike overly fatty foods. Avocado and berries are our favorite ingredients.",
        meal_count=2,
        people_per_meal=[4, 4],
        diet_restrictions=["diabetes"],
        nutrition_targets=["low-sugar"],
        cuisine_likes=["Asian"],
        cuisine_dislikes=[],
        food_likes=["avocado", "berries"],
        food_dislikes=["fatty foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="Develop a hearty Mexican meal for 8 friends, some of whom are allergic to nuts and eggs. Include lots of vegetables and lean proteins.",
        meal_count=1,
        people_per_meal=[8],
        diet_restrictions=["nut allergy", "egg allergy"],
        nutrition_targets=["high-protein"],
        cuisine_likes=["Mexican"],
        cuisine_dislikes=[],
        food_likes=["vegetables"],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create five dinners for two people avoiding all nightshades (tomatoes, peppers, eggplants). Focus on simple, low-fat Mediterranean meals.",
        meal_count=5,
        people_per_meal=[2, 2, 2, 2, 2],
        diet_restrictions=["nightshade intolerance"],
        nutrition_targets=["low-fat"],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["nightshades"]
    ).with_inputs("text"),

    dspy.Example(
        text="I need one special dinner for six people. No pork or shellfish allowed. We want something festive from French or Italian cuisine.",
        meal_count=1,
        people_per_meal=[6],
        diet_restrictions=["no pork", "no shellfish"],
        nutrition_targets=[],
        cuisine_likes=["French", "Italian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan seven healthy meals for one busy person. Must be low-calorie, vegetarian, and favor Middle Eastern flavors. Dislike sweet potatoes.",
        meal_count=7,
        people_per_meal=[1, 1, 1, 1, 1, 1, 1],
        diet_restrictions=["vegetarian"],
        nutrition_targets=["low-calorie"],
        cuisine_likes=["Middle Eastern"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["sweet potatoes"]
    ).with_inputs("text"),

    dspy.Example(
        text="Design two meals for a family of five where one person needs low-sodium food. We enjoy Korean BBQ but dislike sushi.",
        meal_count=2,
        people_per_meal=[5, 5],
        diet_restrictions=["low-sodium"],
        nutrition_targets=[],
        cuisine_likes=["Korean BBQ"],
        cuisine_dislikes=["sushi"],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Suggest three meals for four picky eaters. They dislike mushrooms, broccoli, and prefer comfort food like Italian and American.",
        meal_count=3,
        people_per_meal=[4, 4, 4],
        diet_restrictions=[],
        nutrition_targets=[],
        cuisine_likes=["Italian", "American"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["mushrooms", "broccoli"]
    ).with_inputs("text"),

    dspy.Example(
        text="Help me plan five vegan meals for one person with a peanut allergy. Mediterranean and Asian cuisines are favorites; avoid processed foods.",
        meal_count=5,
        people_per_meal=[1, 1, 1, 1, 1],
        diet_restrictions=["vegan", "peanut allergy"],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean", "Asian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["processed foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare two meals for three people on a high-fiber, low-sugar diet. We love Vietnamese food and dislike overly greasy dishes.",
        meal_count=2,
        people_per_meal=[3, 3],
        diet_restrictions=[],
        nutrition_targets=["high-fiber", "low-sugar"],
        cuisine_likes=["Vietnamese"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["greasy foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan one romantic dinner for two. We prefer French or Italian cuisine, have no restrictions, but want something rich in antioxidants.",
        meal_count=1,
        people_per_meal=[2],
        diet_restrictions=[],
        nutrition_targets=["high-antioxidant"],
        cuisine_likes=["French", "Italian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text= "I need two dinners, one for just me and the other for 8 people. I am vegetarian and am on a low-sodium diet. I hate apples and I love bananas. Italian is my favorite and I dislike Greek.",
        meal_count= 2,
        people_per_meal= [1, 8],
        diet_restrictions= ["vegetarian"],
        nutrition_targets= ["low-sodium"],
        cuisine_likes= ["Italian"],
        cuisine_dislikes= ["Greek"],
        food_likes= ["bananas"],
        food_dislikes= ["apples"]
    ).with_inputs("text"),

    dspy.Example(
        text= "Please plan a fancy Chinese meal for me and my five friends. One friend is allergic to shellfish, another can't eat gluten, and a third is unable to digest dairy. We like fruits and vegetables and lentils.",
        meal_count= 1,
        people_per_meal= [6],
        diet_restrictions= ["shellfish allergy", "gluten allergy", "lactose intolerant"],
        nutrition_targets= [],
        cuisine_likes= ["Chinese"],
        cuisine_dislikes= [],
        food_likes= ["fruits", "vegetables", "lentils"],
        food_dislikes= []
    ).with_inputs("text"),

    dspy.Example(
        text="I'm throwing a casual brunch for 10 friends. Some are vegan, others gluten-free. We'd love Mediterranean vibes, and please avoid anything fried.",
        meal_count=1,
        people_per_meal=[10],
        diet_restrictions=["vegan", "gluten-free"],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["fried foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="For a camping trip, I need five simple meals for a group of six. We'd prefer high-protein options, love Tex-Mex, and can't have dairy products.",
        meal_count=5,
        people_per_meal=[6, 6, 6, 6, 6],
        diet_restrictions=["dairy-free"],
        nutrition_targets=["high-protein"],
        cuisine_likes=["Tex-Mex"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan a romantic dinner and a breakfast-in-bed for two. No dietary restrictions, but I want Mediterranean cuisine and nothing with onions.",
        meal_count=2,
        people_per_meal=[2, 2],
        diet_restrictions=[],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["onions"]
    ).with_inputs("text"),

    dspy.Example(
        text="Help me organize three quick lunches for one busy student who’s vegan, loves Thai food, and needs low-sugar options.",
        meal_count=3,
        people_per_meal=[1, 1, 1],
        diet_restrictions=["vegan"],
        nutrition_targets=["low-sugar"],
        cuisine_likes=["Thai"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="I need four meal ideas for family dinners (group of five). Please make them pescatarian and inspired by Asian or Greek cuisine.",
        meal_count=4,
        people_per_meal=[5, 5, 5, 5],
        diet_restrictions=["pescatarian"],
        nutrition_targets=[],
        cuisine_likes=["Asian", "Greek"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create two hearty meals for a family of six. No peanuts, gluten, or shellfish. Prefer French cuisine and dislike Mexican.",
        meal_count=2,
        people_per_meal=[6, 6],
        diet_restrictions=["peanut allergy", "gluten-free", "shellfish allergy"],
        nutrition_targets=[],
        cuisine_likes=["French"],
        cuisine_dislikes=["Mexican"],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan one elaborate dinner for four adults. Two guests are lactose intolerant. We want a Korean-style menu but no beef or lamb.",
        meal_count=1,
        people_per_meal=[4],
        diet_restrictions=["lactose intolerant"],
        nutrition_targets=[],
        cuisine_likes=["Korean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["beef", "lamb"]
    ).with_inputs("text"),

    dspy.Example(
        text="Could you prepare five kid-friendly meals for three kids? Avoid anything spicy or containing nuts. They love Italian and sandwiches.",
        meal_count=5,
        people_per_meal=[3, 3, 3, 3, 3],
        diet_restrictions=["nut allergy"],
        nutrition_targets=[],
        cuisine_likes=["Italian"],
        cuisine_dislikes=[],
        food_likes=["sandwiches"],
        food_dislikes=["spicy foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="Suggest two festive meals for eight guests at a New Year's Eve party. We need dairy-free options, and everyone loves Japanese and seafood.",
        meal_count=2,
        people_per_meal=[8, 8],
        diet_restrictions=["dairy-free"],
        nutrition_targets=[],
        cuisine_likes=["Japanese"],
        cuisine_dislikes=[],
        food_likes=["seafood"],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="I'm hosting a Thanksgiving dinner for twelve. Two are vegetarian, and three are low-sodium. We love American classics but no heavy gravies.",
        meal_count=1,
        people_per_meal=[12],
        diet_restrictions=["vegetarian", "low-sodium"],
        nutrition_targets=[],
        cuisine_likes=["American"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["heavy gravies"]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan seven meals for one athlete focusing on high-protein and iron-rich foods. Prefers Middle Eastern flavors but hates fish.",
        meal_count=7,
        people_per_meal=[1, 1, 1, 1, 1, 1, 1],
        diet_restrictions=[],
        nutrition_targets=["high-protein", "high-iron"],
        cuisine_likes=["Middle Eastern"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["fish"]
    ).with_inputs("text"),

    dspy.Example(
        text="Could you help me with three easy-to-prep vegan meals for one? I prefer Asian food and dislike tofu and eggplant.",
        meal_count=3,
        people_per_meal=[1, 1, 1],
        diet_restrictions=["vegan"],
        nutrition_targets=[],
        cuisine_likes=["Asian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["tofu", "eggplant"]
    ).with_inputs("text"),

    dspy.Example(
        text="Design five meals for four people where two guests are keto and one is diabetic. We prefer Indian cuisine and can't have anything overly sweet.",
        meal_count=5,
        people_per_meal=[4, 4, 4, 4, 4],
        diet_restrictions=["keto", "diabetes"],
        nutrition_targets=[],
        cuisine_likes=["Indian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["overly sweet foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="I need a single, show-stopping dinner for six people. We're open to anything but prefer Italian and can't have gluten.",
        meal_count=1,
        people_per_meal=[6],
        diet_restrictions=["gluten-free"],
        nutrition_targets=[],
        cuisine_likes=["Italian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan three meals for two adults who eat paleo and want high-fiber options. They love Latin American flavors but dislike overly spicy foods.",
        meal_count=3,
        people_per_meal=[2, 2, 2],
        diet_restrictions=["paleo"],
        nutrition_targets=["high-fiber"],
        cuisine_likes=["Latin American"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["spicy foods"]
    ).with_inputs("text"),

    dspy.Example(
        text="Suggest two comfort meals for a small gathering of six. We prefer American and Southern cuisines, need vegetarian options, and hate mushrooms.",
        meal_count=2,
        people_per_meal=[6, 6],
        diet_restrictions=["vegetarian"],
        nutrition_targets=[],
        cuisine_likes=["American", "Southern"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["mushrooms"]
    ).with_inputs("text"),

    dspy.Example(
        text="For a wellness retreat, create five light meals for eight attendees, all needing low-fat, high-antioxidant dishes inspired by Greek cuisine.",
        meal_count=5,
        people_per_meal=[8, 8, 8, 8, 8],
        diet_restrictions=[],
        nutrition_targets=["low-fat", "high-antioxidant"],
        cuisine_likes=["Greek"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Help me prepare three quick and healthy breakfasts for one vegan person who loves berries and oats but dislikes bananas.",
        meal_count=3,
        people_per_meal=[1, 1, 1],
        diet_restrictions=["vegan"],
        nutrition_targets=[],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=["berries", "oats"],
        food_dislikes=["bananas"]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare a fancy French dinner and a casual lunch for four people. One is allergic to shellfish. Avoid tomatoes and emphasize seasonal vegetables.",
        meal_count=2,
        people_per_meal=[4, 4],
        diet_restrictions=["shellfish allergy"],
        nutrition_targets=[],
        cuisine_likes=["French"],
        cuisine_dislikes=[],
        food_likes=["seasonal vegetables"],
        food_dislikes=["tomatoes"]
    ).with_inputs("text"),

    dspy.Example(
        text="I need a cozy meal plan of five dinners for two adults. No dietary restrictions, but we'd love Japanese and dislike strong citrus flavors.",
        meal_count=5,
        people_per_meal=[2, 2, 2, 2, 2],
        diet_restrictions=[],
        nutrition_targets=[],
        cuisine_likes=["Japanese"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["strong citrus flavors"]
    ).with_inputs("text"),

    dspy.Example(
        text="Design a nutritionally balanced lunch service for a team of 25 employees, ensuring vegan and gluten-free accommodations. Preference for Mediterranean and Asian influences.",
        meal_count=1,
        people_per_meal=[25],
        diet_restrictions=["vegan", "gluten-free"],
        nutrition_targets=["balanced nutrition"],
        cuisine_likes=["Mediterranean", "Asian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Develop three corporate dinner menus for 15 executives, prioritizing low-sodium, heart-healthy meals with French and Californian cuisine inspirations.",
        meal_count=3,
        people_per_meal=[15, 15, 15],
        diet_restrictions=[],
        nutrition_targets=["low-sodium", "heart-healthy"],
        cuisine_likes=["French", "Californian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Curate a formal banquet menu for 100 attendees with multiple dietary needs, including vegetarian, keto, and peanut allergies. Italian and Indian cuisines are preferred.",
        meal_count=1,
        people_per_meal=[100],
        diet_restrictions=["vegetarian", "keto", "peanut allergy"],
        nutrition_targets=[],
        cuisine_likes=["Italian", "Indian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Organize five daily breakfast offerings for a wellness retreat of 12 participants focusing on high-protein, low-fat diets. Asian and Nordic cuisines preferred.",
        meal_count=5,
        people_per_meal=[12, 12, 12, 12, 12],
        diet_restrictions=[],
        nutrition_targets=["high-protein", "low-fat"],
        cuisine_likes=["Asian", "Nordic"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create two gala event menus for 200 guests, including gluten-free, vegan, and lactose-intolerant considerations. Strong preference for upscale American cuisine.",
        meal_count=2,
        people_per_meal=[200, 200],
        diet_restrictions=["gluten-free", "vegan", "lactose intolerant"],
        nutrition_targets=[],
        cuisine_likes=["American"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Develop a single formal lunch menu for a business seminar for 50 attendees, emphasizing Mediterranean flavors and avoiding red meat.",
        meal_count=1,
        people_per_meal=[50],
        diet_restrictions=[],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["red meat"]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare three nutritionally focused menus for a corporate health initiative, targeting low-carb, high-fiber diets for groups of 20 employees.",
        meal_count=3,
        people_per_meal=[20, 20, 20],
        diet_restrictions=[],
        nutrition_targets=["low-carb", "high-fiber"],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Design an executive VIP dinner for 10 guests, ensuring all courses align with pescatarian diets. Preferences include French and Japanese cuisine.",
        meal_count=1,
        people_per_meal=[10],
        diet_restrictions=["pescatarian"],
        nutrition_targets=[],
        cuisine_likes=["French", "Japanese"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan four snack stations for a tech conference of 300 attendees, highlighting vegan, gluten-free, and dairy-free options. Asian and Mediterranean flavors requested.",
        meal_count=4,
        people_per_meal=[300, 300, 300, 300],
        diet_restrictions=["vegan", "gluten-free", "dairy-free"],
        nutrition_targets=[],
        cuisine_likes=["Asian", "Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare a formal three-course dinner menu for a board meeting of 8 participants, ensuring low-sodium and sugar-conscious options. French cuisine emphasis.",
        meal_count=1,
        people_per_meal=[8],
        diet_restrictions=[],
        nutrition_targets=["low-sodium", "low-sugar"],
        cuisine_likes=["French"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Develop five modular lunch boxes for a corporate workshop of 40 employees. Boxes must accommodate vegetarian, gluten-free, and low-sugar needs. Mediterranean style preferred.",
        meal_count=5,
        people_per_meal=[40, 40, 40, 40, 40],
        diet_restrictions=["vegetarian", "gluten-free", "low-sugar"],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create two catering menus for a non-profit fundraiser expecting 60 guests. Ensure vegan-friendly and nut-free dishes. Latin American cuisine preferred.",
        meal_count=2,
        people_per_meal=[60, 60],
        diet_restrictions=["vegan", "nut allergy"],
        nutrition_targets=[],
        cuisine_likes=["Latin American"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Design a two-day meal plan for 15 health-conscious attendees at a leadership retreat. Focus on high-antioxidant and heart-healthy recipes.",
        meal_count=6,
        people_per_meal=[15, 15, 15, 15, 15, 15],
        diet_restrictions=[],
        nutrition_targets=["high-antioxidant", "heart-healthy"],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Organize four upscale cocktail party menus for 80 corporate guests. Highlight seafood and vegetarian options while avoiding red meat and heavy dairy.",
        meal_count=4,
        people_per_meal=[80, 80, 80, 80],
        diet_restrictions=[],
        nutrition_targets=[],
        cuisine_likes=["Seafood-focused", "Vegetarian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["red meat", "heavy dairy"]
    ).with_inputs("text"),

    dspy.Example(
        text="Draft a casual lunch menu for a company sports day for 150 participants, focusing on high-energy foods and low-refined sugars. Prefer American and Mexican cuisines.",
        meal_count=1,
        people_per_meal=[150],
        diet_restrictions=[],
        nutrition_targets=["high-energy", "low-refined sugar"],
        cuisine_likes=["American", "Mexican"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create three rotating meal options for a small hospital conference of 40, ensuring all items are diabetic-friendly, low-sodium, and gluten-free where possible.",
        meal_count=3,
        people_per_meal=[40, 40, 40],
        diet_restrictions=["diabetes", "low-sodium", "gluten-free"],
        nutrition_targets=[],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Design two meal services for an international trade show with 500 participants, accounting for vegetarian, kosher, and halal dietary restrictions.",
        meal_count=2,
        people_per_meal=[500, 500],
        diet_restrictions=["vegetarian", "kosher", "halal"],
        nutrition_targets=[],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare five boxed dinner solutions for a traveling sales team of 12 individuals. Must be shelf-stable, high-protein, and low-sodium with international flavors.",
        meal_count=5,
        people_per_meal=[12, 12, 12, 12, 12],
        diet_restrictions=[],
        nutrition_targets=["shelf-stable", "high-protein", "low-sodium"],
        cuisine_likes=["International"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Organize a series of ten rotating lunch menus for a 30-person corporate office, prioritizing Mediterranean diet principles and weekly vegetarian offerings.",
        meal_count=10,
        people_per_meal=[30]*10,
        diet_restrictions=[],
        nutrition_targets=["Mediterranean diet"],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan an all-day meal service for a corporate training session of 70 staff, including breakfast, lunch, and dinner. Vegan, gluten-free, and dairy-free options required throughout.",
        meal_count=3,
        people_per_meal=[70, 70, 70],
        diet_restrictions=["vegan", "gluten-free", "dairy-free"],
        nutrition_targets=[],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),


]

dev_set = [
    dspy.Example(
        text= "I need a dinner for every night this week. Four of them are for four people and the other three are for just two. I cannot eat tomatoes and my wife can't have tree nuts. We really like American food and don't like Italian. French fries and strawberries are favorites, and we don't like persimmons or spaghetti. My doctor put me on a low-cholesterol diet.",
        meal_count= 7,
        people_per_meal= [4, 4, 4, 4, 2, 2, 2],
        diet_restrictions= ["tomato allergy", "tree nut allergy"],
        nutrition_targets= ["low cholesterol"],
        cuisine_likes= ["American"],
        cuisine_dislikes= ["Chinese"],
        food_likes= ["French fries", "strawberries"],
        food_dislikes= ["persimmons", "spaghetti"]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare a Mediterranean-themed lunch for 22 employees, with both vegan and dairy-free options, minimizing the use of processed grains.",
        meal_count=1,
        people_per_meal=[22],
        diet_restrictions=["vegan", "dairy-free"],
        nutrition_targets=["minimal processed grains"],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan a series of four breakfast buffets for a conference of 120 guests, prioritizing gluten-free, keto-friendly, and nut-free selections, with Scandinavian culinary themes.",
        meal_count=4,
        people_per_meal=[120, 120, 120, 120],
        diet_restrictions=["gluten-free", "keto", "nut allergy"],
        nutrition_targets=[],
        cuisine_likes=["Scandinavian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Create three formal dinner menus for 12 corporate directors focused on heart-healthy, low-sugar, pescatarian meals with Italian and French flavors.",
        meal_count=3,
        people_per_meal=[12, 12, 12],
        diet_restrictions=["pescatarian"],
        nutrition_targets=["heart-healthy", "low-sugar"],
        cuisine_likes=["Italian", "French"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Design five rotating lunchbox menus for a 25-person field team needing low-sodium, vegetarian options that avoid heavy dairy and red meat, with preference for Southeast Asian cuisine.",
        meal_count=5,
        people_per_meal=[25, 25, 25, 25, 25],
        diet_restrictions=["vegetarian"],
        nutrition_targets=["low-sodium"],
        cuisine_likes=["Southeast Asian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=["heavy dairy", "red meat"]
    ).with_inputs("text"),

    dspy.Example(
        text="Organize a single gala dinner for 300 guests focusing on upscale American and fusion Latin cuisines while offering gluten-free and vegan alternatives at every course.",
        meal_count=1,
        people_per_meal=[300],
        diet_restrictions=["gluten-free", "vegan"],
        nutrition_targets=[],
        cuisine_likes=["American", "Latin Fusion"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Assemble a one-day meal service for a medical conference of 80 participants, offering breakfast, lunch, and dinner meals that meet diabetic-friendly and low-fat standards.",
        meal_count=3,
        people_per_meal=[80, 80, 80],
        diet_restrictions=["diabetes"],
        nutrition_targets=["low-fat"],
        cuisine_likes=[],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Draft three snack-focused menus for an indoor company fitness day for 110 staff members, focusing on high-fiber, high-protein, and low-refined-sugar offerings with international influences.",
        meal_count=3,
        people_per_meal=[110, 110, 110],
        diet_restrictions=[],
        nutrition_targets=["high-fiber", "high-protein", "low-refined sugar"],
        cuisine_likes=["International"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Prepare a luxurious five-course dinner plan for 6 C-level executives, with an emphasis on pescatarian dishes, lactose-free preparations, and incorporating French and Japanese elements.",
        meal_count=1,
        people_per_meal=[6],
        diet_restrictions=["pescatarian", "lactose intolerant"],
        nutrition_targets=[],
        cuisine_likes=["French", "Japanese"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Plan an all-day workshop catering service for 50 technology professionals, including vegetarian breakfast, Mediterranean-inspired lunch, and gluten-free Asian dinner.",
        meal_count=3,
        people_per_meal=[50, 50, 50],
        diet_restrictions=["vegetarian", "gluten-free"],
        nutrition_targets=[],
        cuisine_likes=["Mediterranean", "Asian"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text"),

    dspy.Example(
        text="Develop a four-day rotating meal plan for a leadership summit of 35 people, integrating low-carb Mediterranean dishes for lunch and pescatarian-friendly dinners.",
        meal_count=8,
        people_per_meal=[35, 35, 35, 35, 35, 35, 35, 35],
        diet_restrictions=["pescatarian"],
        nutrition_targets=["low-carb"],
        cuisine_likes=["Mediterranean"],
        cuisine_dislikes=[],
        food_likes=[],
        food_dislikes=[]
    ).with_inputs("text")

]