from dspy import Example

train_set = [
    Example(
        text="Plan 5 dinners for a family of three, favoring high-protein and low-carb recipes. Avoid pork and Italian food, but include walleye and American food.",
        output={
            "meal_count": 5,
            "people_per_meal": 3,
            "meal_types": ["dinner"],
            "include_cuisines": ["American"],
            "exclude_cuisines": ["Italian"],
            "diets": [],
            "intolerances": [],
            "include_ingredients": ["walleye"],
            "exclude_ingredients": ["pork"],
            "high_fiber": False,
            "high_protein": True,
            "low_calorie": False,
            "low_carb": True,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Create 3 breakfasts for 2 people that are low in saturated fat and sodium. Include only American cuisine. We are allergic to peanuts, tree nuts, and wheat, but really like french fries.",
        output={
            "meal_count": 3,
            "people_per_meal": 2,
            "meal_types": ["breakfast"],
            "include_cuisines": ["American"],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": ["peanuts","tree nuts","wheat"],
            "include_ingredients": ["french fries"],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": True,
            "low_sodium": True
        }
    ).with_inputs("text"),
    Example(
        text="Build a plan for 7 meals, for 4 people per meal, including only vegetarian dishes that are low in fat and high in fiber.",
        output={
            "meal_count": 7,
            "people_per_meal": 4,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": ["vegetarian"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": True,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Design a 6-meal plan with Asian-inspired dinners for 2 people, avoiding all dairy and focusing on low cholesterol. One person is vegetarian, another is gluten free.",
        output={
            "meal_count": 6,
            "people_per_meal": 2,
            "meal_types": ["dinner"],
            "include_cuisines": ["Asian"],
            "exclude_cuisines": [],
            "diets": ["vegetarian","gluten free"],
            "intolerances": ["dairy"],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": True,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Prepare 4 meals for 1 person, avoiding spicy ingredients and Indian cuisine. Emphasize low sodium and low fat. We like Greek food and persimmons.",
        output={
            "meal_count": 4,
            "people_per_meal": 1,
            "meal_types": [],
            "include_cuisines": ["Greek"],
            "exclude_cuisines": ["Indian"],
            "diets": [],
            "intolerances": [],
            "include_ingredients": ["persimmons"],
            "exclude_ingredients": ["chili", "pepper", "hot sauce"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": True
        }
    ).with_inputs("text"),
    Example(
        text="Generate 3 breakfasts and 3 lunches for 2 people, focused on Mediterranean and Japanese cuisines, high in protein and fiber. We don't like carrots or potatoes.",
        output={
            "meal_count": 6,
            "people_per_meal": 2,
            "meal_types": ["breakfast"],
            "include_cuisines": ["Mediterranean", "Japanese"],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["carrots", "potatoes"],
            "high_fiber": True,
            "high_protein": True,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Build a keto-friendly plan for 5 dinners serving 3 people each, avoiding any grains or sugar. include lettuce.",
        output={
            "meal_count": 5,
            "people_per_meal": 3,
            "meal_types": ["dinner"],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": ["keto"],
            "intolerances": [],
            "include_ingredients": ["lettuce"],
            "exclude_ingredients": ["grains", "sugar"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": True,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Make a 7-day vegan meal plan for 1 person per meal, avoiding soy and ensuring low fat and low saturated fat.",
        output={
            "meal_count": 7,
            "people_per_meal": 1,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": ["vegan"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["soy"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": True,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Create 4 meals for a working group of six as a pescatarian diet with high fiber, avoiding all red meats and fried ingredients.",
        output={
            "meal_count": 4,
            "people_per_meal": 6,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": ["pescatarian"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["beef", "lamb", "fried"],
            "high_fiber": True,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Develop 6 Mediterranean meals for my partner and I with a focus on high-protein and low-cholesterol ingredients, excluding eggs and cheese.",
        output={
            "meal_count": 6,
            "people_per_meal": 2,
            "meal_types": [],
            "include_cuisines": ["Mediterranean"],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["eggs", "cheese"],
            "high_fiber": False,
            "high_protein": True,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": True,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Prepare 5 meals for 2 people each, focusing on gluten-free, high-fiber dishes. Exclude French cuisine and mushrooms.",
        output={
            "meal_count": 5,
            "people_per_meal": 2,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": ["French"],
            "diets": ["gluten_free"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["mushrooms"],
            "high_fiber": True,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Generate a low-calorie meal plan of 4 lunches and 2 dinners, serving 1 person per meal. Avoid red meat and Chinese cuisine.",
        output={
            "meal_count": 6,
            "people_per_meal": 1,
            "meal_types": ["dinner"],
            "include_cuisines": [],
            "exclude_cuisines": ["Chinese"],
            "diets": [],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["beef", "lamb"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": True,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Design 3 dinners for 3 people each with low sodium and low fat, and include Indian cuisine only.",
        output={
            "meal_count": 3,
            "people_per_meal": 3,
            "meal_types": ["dinner"],
            "include_cuisines": ["Indian"],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": True
        }
    ).with_inputs("text"),
    Example(
        text="Create 8 high-protein breakfasts for a group of 4, ensuring all recipes are dairy-free and soy-free.",
        output={
            "meal_count": 8,
            "people_per_meal": 4,
            "meal_types": ["breakfast"],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": ["dairy", "soy"],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": True,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Plan 4 vegan lunches for 2 people each that are low in cholesterol and saturated fat, and avoid Thai cuisine.",
        output={
            "meal_count": 4,
            "people_per_meal": 2,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": ["Thai"],
            "diets": ["vegan"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": True,
            "low_sat_fat": True,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Design 3 meals for 1 person each that follow a low-carb, high-fiber plan and include Mexican cuisine.",
        output={
            "meal_count": 3,
            "people_per_meal": 1,
            "meal_types": [],
            "include_cuisines": ["Mexican"],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": True,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": True,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Generate 5 pescatarian dinners for 2 people that avoid dairy and eggs and are low in fat and calories.",
        output={
            "meal_count": 5,
            "people_per_meal": 2,
            "meal_types": ["dinner"],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": ["pescatarian"],
            "intolerances": ["dairy"],
            "include_ingredients": [],
            "exclude_ingredients": ["eggs"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": True,
            "low_carb": False,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Prepare 6 low-fat and low-sodium Mediterranean meals for a family of 3, excluding garlic and onions and including salmon.",
        output={
            "meal_count": 6,
            "people_per_meal": 3,
            "meal_types": [],
            "include_cuisines": ["Mediterranean"],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": [],
            "include_ingredients": ["salmon"],
            "exclude_ingredients": ["garlic", "onions"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": True
        }
    ).with_inputs("text"),
    Example(
        text="Create 4 gluten-free and dairy-free lunches for my son and I that are low in cholesterol and include Asian flavors. We like chives and sesame seeds and don't like salmon.",
        output={
            "meal_count": 4,
            "people_per_meal": 2,
            "meal_types": [],
            "include_cuisines": ["Asian"],
            "exclude_cuisines": [],
            "diets": ["gluten_free"],
            "intolerances": ["dairy"],
            "include_ingredients": ["chives","sesame seeds"],
            "exclude_ingredients": ["salmon"],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": True,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Design a 7-day meal plan for 2 people per meal with high fiber, low sodium, and no peanuts or shellfish. We have rice and tomatoes, and do not like peaches.",
        output={
            "meal_count": 7,
            "people_per_meal": 2,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": ["peanuts", "shellfish"],
            "include_ingredients": ["rice","tomatoes"],
            "exclude_ingredients": ["peaches"],
            "high_fiber": True,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": True
        }
    ).with_inputs("text"),
]

dev_set = [
    Example(
        text="Generate 3 high-protein dinners for 2 adults, excluding pork and Italian cuisine.",
        output={
            "meal_count": 3,
            "people_per_meal": 2,
            "meal_types": ["dinner"],
            "include_cuisines": [],
            "exclude_cuisines": ["Italian"],
            "diets": [],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["pork"],
            "high_fiber": False,
            "high_protein": True,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Plan 5 vegetarian breakfasts for 1 person each, ensuring low saturated fat and excluding Indian cuisine.",
        output={
            "meal_count": 5,
            "people_per_meal": 1,
            "meal_types": ["breakfast"],
            "include_cuisines": [],
            "exclude_cuisines": ["Indian"],
            "diets": ["vegetarian"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": True,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Create 6 Mediterranean lunches for a group of 3, avoiding gluten and ensuring low sodium.",
        output={
            "meal_count": 6,
            "people_per_meal": 3,
            "meal_types": [],
            "include_cuisines": ["Mediterranean"],
            "exclude_cuisines": [],
            "diets": ["gluten_free"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": True
        }
    ).with_inputs("text"),
    Example(
        text="Design a low-fat, low-carb dinner plan for 2 people over 4 days, avoiding dairy and soy.",
        output={
            "meal_count": 4,
            "people_per_meal": 2,
            "meal_types": ["dinner"],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": [],
            "intolerances": ["dairy", "soy"],
            "include_ingredients": [],
            "exclude_ingredients": [],
            "high_fiber": False,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": True,
            "low_fat": True,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
    Example(
        text="Prepare 7 meals for a family of 4 that are high in fiber, exclude peanuts, and follow a vegan diet.",
        output={
            "meal_count": 7,
            "people_per_meal": 4,
            "meal_types": [],
            "include_cuisines": [],
            "exclude_cuisines": [],
            "diets": ["vegan"],
            "intolerances": [],
            "include_ingredients": [],
            "exclude_ingredients": ["peanuts"],
            "high_fiber": True,
            "high_protein": False,
            "low_calorie": False,
            "low_carb": False,
            "low_fat": False,
            "low_cholesterol": False,
            "low_sat_fat": False,
            "low_sodium": False
        }
    ).with_inputs("text"),
]
